export enum EFiatCurrency {
    EUR = "EUR",
    USD = "USD",
    JPY = "JPY",
    GBP = "GBP",
    AUD = "AUD",
    NZD = "NZD",
    CAD = "CAD",
    SEK = "SEK",
    CHF = "CHF",
    HUF = "HUF",
    CNY = "CNY",
    HKD = "HKD",
    SGD = "SGD",
    INR = "INR",
    MXN = "MXN",
    PHP = "PHP",
    IDR = "IDR",
    THB = "THB",
    MYR = "MYR",
    ZAR = "ZAR"
}

export enum ECryptoCurrency {
    BTC = "BTC",
    ETH = "ETH",
    XRP = "XRP",
    USDT = "USDT",
    BNB = "BNB",
    SOL = "SOL",
    USDC = "USDC",
    DOGE = "DOGE",
    ADA = "ADA",
    STETH = "STETH",
    WTRX = "WTRX",
    TRX = "TRX",
    WBTC = "WBTC",
    WSTETH = "WSTETH",
    LINK = "LINK",
    AVAX = "AVAX",
    SUI20947 = "SUI20947",
    XLM = "XLM",
    LTC = "LTC",
    WETH = "WETH",
    TON11419 = "TON11419",
    SHIB = "SHIB",
    LEO = "LEO",
    HBAR = "HBAR",
    USDS33039 = "USDS33039"
}